"""Canonical PostgreSQL baseline for the offline SQLite cutover harness.

Revision ID: 0001_pg_baseline
Revises: None
"""

from collections.abc import Sequence

from alembic import op


revision: str = "0001_pg_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TABLE_DDL = (
    """CREATE TABLE members (
        user_id BIGINT NOT NULL, full_name TEXT, username TEXT, phone TEXT,
        city TEXT, help_type TEXT, transport TEXT, availability TEXT, about TEXT,
        tags TEXT, application_note TEXT, role TEXT NOT NULL DEFAULT 'candidate',
        status TEXT NOT NULL DEFAULT 'pending', bonus BIGINT NOT NULL DEFAULT 0,
        done_count BIGINT NOT NULL DEFAULT 0, referred_by BIGINT,
        created_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, approved_by BIGINT,
        applied_at TIMESTAMPTZ, chat_xp BIGINT NOT NULL DEFAULT 0,
        ref_confirmed BOOLEAN NOT NULL DEFAULT false,
        CONSTRAINT pk_members PRIMARY KEY (user_id)
    )""",
    """CREATE TABLE tasks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        type TEXT NOT NULL, title TEXT NOT NULL, details TEXT,
        lat DOUBLE PRECISION, lng DOUBLE PRECISION, address TEXT, city TEXT,
        reward BIGINT NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'open',
        created_by BIGINT, created_at TIMESTAMPTZ, claimed_by BIGINT,
        claimed_at TIMESTAMPTZ, done_at TIMESTAMPTZ, proof_note TEXT,
        review_note TEXT, assigned_to BIGINT, slot_start TIMESTAMPTZ,
        slot_end TIMESTAMPTZ, repeatable BOOLEAN NOT NULL DEFAULT false,
        photo_file TEXT, photo_media_id TEXT, operation_id TEXT, request_hash TEXT,
        completion_operation_id TEXT, completion_request_hash TEXT,
        submission_attempt INTEGER NOT NULL DEFAULT 0,
        evidence_policy TEXT NOT NULL DEFAULT 'none', max_participants INTEGER,
        budget_cap BIGINT, cancel_operation_id TEXT, cancel_request_hash TEXT,
        cancelled_at TIMESTAMPTZ, cancelled_by BIGINT, cancel_reason TEXT,
        expired_at TIMESTAMPTZ, version INTEGER NOT NULL DEFAULT 1,
        CONSTRAINT pk_tasks PRIMARY KEY (id)
    )""",
    """CREATE TABLE bonus_ledger (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        user_id BIGINT NOT NULL, amount BIGINT NOT NULL, reason TEXT NOT NULL,
        task_id BIGINT, assignment_id BIGINT, withdrawal_id BIGINT,
        created_by BIGINT, created_at TIMESTAMPTZ, operation_id TEXT,
        balance_after BIGINT, CONSTRAINT pk_bonus_ledger PRIMARY KEY (id),
        CONSTRAINT fk_bonus_ledger_user_id_members FOREIGN KEY (user_id)
            REFERENCES members (user_id) ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED
    )""",
    """CREATE TABLE referral_rewards (
        referee_id BIGINT NOT NULL, referrer_id BIGINT NOT NULL,
        amount BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_referral_rewards PRIMARY KEY (referee_id)
    )""",
    """CREATE TABLE referral_tokens (
        token TEXT NOT NULL, referrer_id BIGINT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_referral_tokens PRIMARY KEY (token)
    )""",
    """CREATE TABLE referral_milestone_rewards (
        user_id BIGINT NOT NULL, threshold INTEGER NOT NULL, amount BIGINT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_referral_milestone_rewards PRIMARY KEY (user_id, threshold)
    )""",
    """CREATE TABLE task_assignments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        task_id BIGINT NOT NULL, user_id BIGINT NOT NULL,
        status TEXT NOT NULL DEFAULT 'claimed', claimed_at TIMESTAMPTZ NOT NULL,
        done_at TIMESTAMPTZ, proof_note TEXT, review_note TEXT,
        completion_operation_id TEXT, completion_request_hash TEXT,
        submission_attempt INTEGER NOT NULL DEFAULT 0, reward_snapshot BIGINT,
        due_at TIMESTAMPTZ, revision_due_at TIMESTAMPTZ,
        release_operation_id TEXT, release_request_hash TEXT,
        released_at TIMESTAMPTZ, release_reason TEXT, terminal_at TIMESTAMPTZ,
        terminal_by BIGINT, terminal_reason TEXT, decision_operation_id TEXT,
        decision_request_hash TEXT, version INTEGER NOT NULL DEFAULT 1,
        CONSTRAINT pk_task_assignments PRIMARY KEY (id),
        CONSTRAINT fk_task_assignments_task_id_tasks FOREIGN KEY (task_id)
            REFERENCES tasks (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT fk_task_assignments_user_id_members FOREIGN KEY (user_id)
            REFERENCES members (user_id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
    )""",
    """CREATE TABLE task_evidence (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        assignment_id BIGINT, task_id BIGINT NOT NULL, user_id BIGINT NOT NULL,
        kind TEXT NOT NULL, photo_file TEXT NOT NULL, media_id TEXT,
        sha256 TEXT NOT NULL, submission_operation_id TEXT,
        attempt INTEGER NOT NULL DEFAULT 1, is_current BOOLEAN NOT NULL DEFAULT true,
        created_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_task_evidence PRIMARY KEY (id),
        CONSTRAINT fk_task_evidence_assignment_id_task_assignments
            FOREIGN KEY (assignment_id) REFERENCES task_assignments (id)
            ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT fk_task_evidence_task_id_tasks FOREIGN KEY (task_id)
            REFERENCES tasks (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT fk_task_evidence_user_id_members FOREIGN KEY (user_id)
            REFERENCES members (user_id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
    )""",
    """CREATE TABLE media_objects (
        id TEXT NOT NULL, backend TEXT NOT NULL, object_key TEXT NOT NULL,
        purpose TEXT NOT NULL, state TEXT NOT NULL, content_type TEXT NOT NULL,
        size_bytes BIGINT NOT NULL, sha256 TEXT NOT NULL,
        upload_operation_id TEXT NOT NULL, request_hash TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL, ready_at TIMESTAMPTZ,
        delete_after TIMESTAMPTZ, deleted_at TIMESTAMPTZ, last_error TEXT,
        reconcile_attempts INTEGER NOT NULL DEFAULT 0, version_id TEXT,
        checked_at TIMESTAMPTZ, CONSTRAINT pk_media_objects PRIMARY KEY (id),
        CONSTRAINT uq_media_objects_upload_operation_id UNIQUE (upload_operation_id),
        CONSTRAINT uq_media_objects_backend_object_key UNIQUE (backend, object_key)
    )""",
    """CREATE TABLE withdrawal_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        user_id BIGINT NOT NULL, amount BIGINT NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ NOT NULL,
        decided_by BIGINT, decided_at TIMESTAMPTZ, note TEXT, operation_id TEXT,
        request_hash TEXT, account_type TEXT, account_ciphertext TEXT,
        account_masked TEXT, account_fingerprint TEXT, key_version INTEGER,
        decision_operation_id TEXT, decision_request_hash TEXT, provider TEXT,
        external_reference TEXT, external_reference_canonical TEXT,
        reject_reason TEXT, account_purged_at TIMESTAMPTZ,
        processing_by BIGINT, processing_at TIMESTAMPTZ,
        CONSTRAINT pk_withdrawal_requests PRIMARY KEY (id)
    )""",
    """CREATE TABLE withdrawal_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        withdrawal_id BIGINT NOT NULL, event_type TEXT NOT NULL, from_status TEXT,
        to_status TEXT NOT NULL, actor_id BIGINT, operation_id TEXT,
        created_at TIMESTAMPTZ NOT NULL,
        metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        CONSTRAINT pk_withdrawal_events PRIMARY KEY (id),
        CONSTRAINT fk_withdrawal_events_withdrawal_id_withdrawal_requests
            FOREIGN KEY (withdrawal_id) REFERENCES withdrawal_requests (id)
            ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
    )""",
    """CREATE TABLE task_review_commands (
        operation_id TEXT NOT NULL, assignment_id BIGINT NOT NULL,
        request_hash TEXT NOT NULL, result_status TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_task_review_commands PRIMARY KEY (operation_id),
        CONSTRAINT fk_task_review_commands_assignment_id_task_assignments
            FOREIGN KEY (assignment_id) REFERENCES task_assignments (id)
            ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
    )""",
    """CREATE TABLE task_completion_commands (
        operation_id TEXT NOT NULL, assignment_id BIGINT NOT NULL,
        request_hash TEXT NOT NULL, result_status TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_task_completion_commands PRIMARY KEY (operation_id),
        CONSTRAINT fk_task_completion_commands_assignment_id_task_assignments
            FOREIGN KEY (assignment_id) REFERENCES task_assignments (id)
            ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
    )""",
    """CREATE TABLE task_outbox (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        event_key TEXT NOT NULL, event_type TEXT NOT NULL, recipient_id BIGINT,
        chat_id TEXT, topic_id BIGINT, media_id TEXT, payload_json JSONB NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0,
        available_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL,
        sent_at TIMESTAMPTZ, telegram_message_id BIGINT, telegram_thread_id BIGINT,
        last_error TEXT,
        CONSTRAINT pk_task_outbox PRIMARY KEY (id),
        CONSTRAINT uq_task_outbox_event_key UNIQUE (event_key)
    )""",
    """CREATE TABLE telegram_update_inbox (
        update_id BIGINT NOT NULL, payload_json TEXT, payload_sha256 TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0,
        available_at TIMESTAMPTZ NOT NULL, received_at TIMESTAMPTZ NOT NULL,
        processed_at TIMESTAMPTZ, last_error TEXT, locked_by TEXT,
        locked_at TIMESTAMPTZ, dead_at TIMESTAMPTZ, redrive_operation_id TEXT,
        redrive_request_hash TEXT, redrive_reason TEXT, redriven_by BIGINT,
        redriven_at TIMESTAMPTZ,
        CONSTRAINT pk_telegram_update_inbox PRIMARY KEY (update_id)
    )""",
    """CREATE TABLE telegram_update_effects (
        update_id BIGINT NOT NULL, effect_key TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_telegram_update_effects PRIMARY KEY (update_id, effect_key)
    )""",
    """CREATE TABLE telegram_update_redrive_commands (
        operation_id TEXT NOT NULL, request_hash TEXT NOT NULL,
        update_id BIGINT NOT NULL, admin_id BIGINT NOT NULL, reason TEXT NOT NULL,
        result_status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_telegram_update_redrive_commands PRIMARY KEY (operation_id)
    )""",
    """CREATE TABLE chat_activity (
        user_id BIGINT NOT NULL, last_msg_at TIMESTAMPTZ, day DATE,
        msg_xp_today BIGINT NOT NULL DEFAULT 0,
        thanks_xp_today BIGINT NOT NULL DEFAULT 0,
        messages_total BIGINT NOT NULL DEFAULT 0,
        thanks_total BIGINT NOT NULL DEFAULT 0,
        CONSTRAINT pk_chat_activity PRIMARY KEY (user_id)
    )""",
    """CREATE TABLE analytics_subjects (
        subject_id TEXT NOT NULL, user_id BIGINT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_analytics_subjects PRIMARY KEY (subject_id),
        CONSTRAINT uq_analytics_subjects_user_id UNIQUE (user_id)
    )""",
    """CREATE TABLE product_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        event_id TEXT NOT NULL, occurred_at TIMESTAMPTZ NOT NULL,
        event_name TEXT NOT NULL, source TEXT NOT NULL, subject_id TEXT,
        session_id TEXT, task_id BIGINT, assignment_id BIGINT, outcome TEXT,
        reason_code TEXT, properties_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        dedupe_key TEXT, schema_version INTEGER NOT NULL DEFAULT 1,
        expires_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_product_events PRIMARY KEY (id),
        CONSTRAINT uq_product_events_event_id UNIQUE (event_id)
    )""",
    """CREATE TABLE published_posts (
        kind TEXT NOT NULL, chat_id BIGINT NOT NULL, topic BIGINT,
        message_ids JSONB NOT NULL, published_at TIMESTAMPTZ NOT NULL,
        published_by BIGINT, operation_id TEXT,
        CONSTRAINT pk_published_posts PRIMARY KEY (kind)
    )""",
    """CREATE TABLE publication_jobs (
        kind TEXT NOT NULL, operation_id TEXT NOT NULL, status TEXT NOT NULL,
        requested_by BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL,
        completed_at TIMESTAMPTZ,
        CONSTRAINT pk_publication_jobs PRIMARY KEY (kind),
        CONSTRAINT uq_publication_jobs_operation_id UNIQUE (operation_id)
    )""",
    """CREATE TABLE publication_delivery_parts (
        operation_id TEXT NOT NULL, part_index INTEGER NOT NULL,
        message_id BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_publication_delivery_parts PRIMARY KEY (operation_id, part_index)
    )""",
    """CREATE TABLE publication_cleanup_messages (
        operation_id TEXT NOT NULL, chat_id TEXT NOT NULL, message_id BIGINT NOT NULL,
        final_job_status TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending',
        attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT,
        deleted_at TIMESTAMPTZ,
        CONSTRAINT pk_publication_cleanup_messages
            PRIMARY KEY (operation_id, chat_id, message_id)
    )""",
    """CREATE TABLE thanks_pairs (
        from_id BIGINT NOT NULL, to_id BIGINT NOT NULL, last_at TIMESTAMPTZ NOT NULL,
        CONSTRAINT pk_thanks_pairs PRIMARY KEY (from_id, to_id)
    )""",
    """CREATE TABLE awards (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        code TEXT, emoji TEXT NOT NULL DEFAULT U&'\+01F3C5', title TEXT NOT NULL,
        description TEXT, bonus BIGINT NOT NULL DEFAULT 0,
        repeatable BOOLEAN NOT NULL DEFAULT true,
        active BOOLEAN NOT NULL DEFAULT true, created_by BIGINT,
        created_at TIMESTAMPTZ, CONSTRAINT pk_awards PRIMARY KEY (id),
        CONSTRAINT uq_awards_code UNIQUE (code)
    )""",
    """CREATE TABLE member_awards (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        user_id BIGINT NOT NULL, award_id BIGINT NOT NULL,
        slot TEXT NOT NULL DEFAULT '', bonus BIGINT NOT NULL DEFAULT 0,
        note TEXT, granted_by BIGINT, granted_at TIMESTAMPTZ NOT NULL,
        operation_id TEXT, balance_after BIGINT, revoked_at TIMESTAMPTZ,
        revoked_by BIGINT, CONSTRAINT pk_member_awards PRIMARY KEY (id),
        CONSTRAINT uq_member_awards_user_award_slot UNIQUE (user_id, award_id, slot),
        CONSTRAINT fk_member_awards_user_id_members FOREIGN KEY (user_id)
            REFERENCES members (user_id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT fk_member_awards_award_id_awards FOREIGN KEY (award_id)
            REFERENCES awards (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
    )""",
)


INDEX_DDL = (
    "CREATE INDEX idx_tasks_status ON tasks (status)",
    "CREATE INDEX idx_tasks_assigned ON tasks (assigned_to, status)",
    "CREATE INDEX idx_task_assignments_user ON task_assignments (user_id, status)",
    "CREATE INDEX idx_task_assignments_review ON task_assignments (status, task_id)",
    "CREATE UNIQUE INDEX idx_assignment_one_active ON task_assignments (task_id, user_id) WHERE status IN ('claimed', 'review')",
    "CREATE UNIQUE INDEX idx_assignment_one_done ON task_assignments (task_id, user_id) WHERE status = 'done'",
    "CREATE UNIQUE INDEX idx_assignment_decision_operation ON task_assignments (decision_operation_id) WHERE decision_operation_id IS NOT NULL",
    "CREATE INDEX idx_withdrawals_user ON withdrawal_requests (user_id, created_at)",
    "CREATE UNIQUE INDEX idx_withdrawals_one_pending ON withdrawal_requests (user_id) WHERE status IN ('pending', 'processing')",
    "CREATE UNIQUE INDEX idx_withdrawals_operation ON withdrawal_requests (operation_id) WHERE operation_id IS NOT NULL",
    "CREATE UNIQUE INDEX idx_withdrawals_decision_operation ON withdrawal_requests (decision_operation_id) WHERE decision_operation_id IS NOT NULL",
    "CREATE UNIQUE INDEX idx_withdrawals_external_reference_canonical ON withdrawal_requests (provider, external_reference_canonical) WHERE status = 'completed' AND external_reference_canonical IS NOT NULL",
    "CREATE INDEX idx_withdrawal_events_request ON withdrawal_events (withdrawal_id, id)",
    "CREATE INDEX idx_ledger_user ON bonus_ledger (user_id)",
    "CREATE UNIQUE INDEX idx_ledger_operation ON bonus_ledger (operation_id) WHERE operation_id IS NOT NULL",
    "CREATE UNIQUE INDEX idx_tasks_operation ON tasks (operation_id) WHERE operation_id IS NOT NULL",
    "CREATE INDEX idx_task_evidence_task ON task_evidence (task_id, assignment_id, user_id)",
    "CREATE UNIQUE INDEX idx_tasks_completion_operation ON tasks (completion_operation_id) WHERE completion_operation_id IS NOT NULL",
    "CREATE UNIQUE INDEX idx_tasks_cancel_operation ON tasks (cancel_operation_id) WHERE cancel_operation_id IS NOT NULL",
    "CREATE UNIQUE INDEX idx_assignments_completion_operation ON task_assignments (completion_operation_id) WHERE completion_operation_id IS NOT NULL",
    "CREATE UNIQUE INDEX idx_assignments_release_operation ON task_assignments (release_operation_id) WHERE release_operation_id IS NOT NULL",
    "CREATE INDEX idx_member_awards_user ON member_awards (user_id, granted_at)",
    "CREATE UNIQUE INDEX idx_member_awards_operation ON member_awards (operation_id) WHERE operation_id IS NOT NULL",
    "CREATE INDEX idx_task_outbox_delivery ON task_outbox (status, available_at, id)",
    "CREATE INDEX idx_telegram_inbox_delivery ON telegram_update_inbox (status, available_at, update_id)",
    "CREATE UNIQUE INDEX idx_telegram_inbox_redrive_operation ON telegram_update_inbox (redrive_operation_id) WHERE redrive_operation_id IS NOT NULL",
    "CREATE INDEX idx_media_gc ON media_objects (state, delete_after)",
    "CREATE UNIQUE INDEX idx_product_events_dedupe ON product_events (dedupe_key) WHERE dedupe_key IS NOT NULL",
    "CREATE INDEX idx_product_events_funnel ON product_events (event_name, occurred_at)",
    "CREATE INDEX idx_product_events_subject ON product_events (subject_id, occurred_at)",
    "CREATE INDEX idx_product_events_task ON product_events (task_id, occurred_at) WHERE task_id IS NOT NULL",
    "CREATE INDEX idx_product_events_expiry ON product_events (expires_at)",
)


DROP_ORDER = (
    "member_awards", "awards", "thanks_pairs", "publication_cleanup_messages",
    "publication_delivery_parts", "publication_jobs", "published_posts",
    "product_events", "analytics_subjects", "chat_activity",
    "telegram_update_redrive_commands", "telegram_update_effects",
    "telegram_update_inbox", "task_outbox", "task_completion_commands",
    "task_review_commands", "withdrawal_events", "withdrawal_requests",
    "media_objects", "task_evidence", "task_assignments",
    "referral_milestone_rewards", "referral_tokens", "referral_rewards",
    "bonus_ledger", "tasks", "members",
)


if len(TABLE_DDL) != 27 or len(INDEX_DDL) != 32:
    raise RuntimeError("PostgreSQL baseline inventory is incomplete")


def upgrade() -> None:
    for statement in TABLE_DDL:
        op.execute(statement)
    for statement in INDEX_DDL:
        op.execute(statement)


def downgrade() -> None:
    raise RuntimeError(
        "Destructive baseline downgrade is disabled. Restore the verified pre-cutover "
        "backup or deploy a forward corrective migration."
    )
