"""Add dispute controls and audited member city-change requests.

Revision ID: 0002_pilot_reliability
Revises: 0001_pg_baseline
"""

from collections.abc import Sequence

from alembic import op


revision: str = "0002_pilot_reliability"
down_revision: str | None = "0001_pg_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("ALTER TABLE members ADD COLUMN city_change_requested TEXT")
    op.execute("ALTER TABLE members ADD COLUMN city_change_requested_at TIMESTAMPTZ")
    op.execute("""
        CREATE TABLE task_disputes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            assignment_id BIGINT NOT NULL, task_id BIGINT NOT NULL,
            user_id BIGINT NOT NULL, reward BIGINT NOT NULL, reason TEXT NOT NULL,
            reconciliation_reason TEXT,
            reconciliation_reference TEXT,
            status TEXT NOT NULL DEFAULT 'pending', opened_by BIGINT NOT NULL,
            opened_at TIMESTAMPTZ NOT NULL, open_operation_id TEXT NOT NULL,
            open_request_hash TEXT NOT NULL, decided_by BIGINT,
            decided_at TIMESTAMPTZ, decision_note TEXT,
            decision_operation_id TEXT, decision_request_hash TEXT,
            CONSTRAINT pk_task_disputes PRIMARY KEY (id),
            CONSTRAINT uq_task_disputes_assignment_id UNIQUE (assignment_id),
            CONSTRAINT uq_task_disputes_open_operation_id UNIQUE (open_operation_id),
            CONSTRAINT uq_task_disputes_decision_operation_id UNIQUE (decision_operation_id),
            CONSTRAINT fk_task_disputes_assignment_id_task_assignments
                FOREIGN KEY (assignment_id) REFERENCES task_assignments (id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
        )
    """)
    op.execute(
        "CREATE INDEX idx_task_disputes_status "
        "ON task_disputes (status, opened_at, id)"
    )
    op.execute("ALTER TABLE member_awards ADD COLUMN revoke_note TEXT")
    op.execute("ALTER TABLE member_awards ADD COLUMN revoke_operation_id TEXT")
    op.execute("ALTER TABLE member_awards ADD COLUMN revoke_request_hash TEXT")
    op.execute(
        "CREATE UNIQUE INDEX idx_member_awards_revoke_operation "
        "ON member_awards (revoke_operation_id) "
        "WHERE revoke_operation_id IS NOT NULL"
    )


def downgrade() -> None:
    raise RuntimeError(
        "Destructive pilot-reliability downgrade is disabled. Restore a verified "
        "backup or deploy a forward corrective migration."
    )
