"""Add bounded manual grants and maker-checker admin role changes.

Revision ID: 0003_admin_financial_controls
Revises: 0002_pilot_reliability
"""

from collections.abc import Sequence

from alembic import op


revision: str = "0003_admin_financial_controls"
down_revision: str | None = "0002_pilot_reliability"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE manual_grant_commands (
            operation_id TEXT NOT NULL, request_hash TEXT NOT NULL,
            user_id BIGINT NOT NULL, amount BIGINT NOT NULL, reason TEXT NOT NULL,
            maker_id BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL,
            ledger_id BIGINT NOT NULL, result_balance BIGINT NOT NULL,
            CONSTRAINT pk_manual_grant_commands PRIMARY KEY (operation_id),
            CONSTRAINT fk_manual_grant_user FOREIGN KEY (user_id)
                REFERENCES members (user_id) ON DELETE RESTRICT,
            CONSTRAINT fk_manual_grant_maker FOREIGN KEY (maker_id)
                REFERENCES members (user_id) ON DELETE RESTRICT,
            CONSTRAINT fk_manual_grant_ledger FOREIGN KEY (ledger_id)
                REFERENCES bonus_ledger (id) ON DELETE RESTRICT,
            CONSTRAINT ck_manual_grant_positive CHECK (amount BETWEEN 1 AND 200),
            CONSTRAINT ck_manual_grant_distinct CHECK (maker_id <> user_id)
        )
    """)
    op.execute(
        "CREATE INDEX idx_manual_grants_maker_time "
        "ON manual_grant_commands (maker_id, created_at)"
    )
    op.execute(
        "CREATE INDEX idx_manual_grants_recipient_time "
        "ON manual_grant_commands (user_id, created_at)"
    )
    op.execute("""
        CREATE TABLE admin_role_changes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id BIGINT NOT NULL, from_role TEXT NOT NULL, to_role TEXT NOT NULL,
            reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending',
            requested_by BIGINT NOT NULL, requested_at TIMESTAMPTZ NOT NULL,
            request_operation_id TEXT NOT NULL, request_hash TEXT NOT NULL,
            decided_by BIGINT, decided_at TIMESTAMPTZ, decision_note TEXT,
            decision_operation_id TEXT, decision_hash TEXT,
            CONSTRAINT pk_admin_role_changes PRIMARY KEY (id),
            CONSTRAINT uq_admin_role_request_operation UNIQUE (request_operation_id),
            CONSTRAINT uq_admin_role_decision_operation UNIQUE (decision_operation_id),
            CONSTRAINT fk_admin_role_target FOREIGN KEY (user_id)
                REFERENCES members (user_id) ON DELETE RESTRICT,
            CONSTRAINT fk_admin_role_maker FOREIGN KEY (requested_by)
                REFERENCES members (user_id) ON DELETE RESTRICT,
            CONSTRAINT fk_admin_role_checker FOREIGN KEY (decided_by)
                REFERENCES members (user_id) ON DELETE RESTRICT,
            CONSTRAINT ck_admin_role_distinct CHECK (from_role <> to_role),
            CONSTRAINT ck_admin_role_status CHECK (status IN ('pending','applied','rejected')),
            CONSTRAINT ck_admin_role_maker_target CHECK (requested_by <> user_id),
            CONSTRAINT ck_admin_role_checker_distinct CHECK (
                decided_by IS NULL OR (
                    decided_by <> requested_by AND decided_by <> user_id
                )
            )
        )
    """)
    op.execute(
        "CREATE INDEX idx_admin_role_changes_status "
        "ON admin_role_changes (status, requested_at, id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_admin_role_change_one_pending "
        "ON admin_role_changes (user_id) WHERE status='pending'"
    )


def downgrade() -> None:
    raise RuntimeError(
        "Destructive admin-financial-controls downgrade is disabled. Restore a "
        "verified backup or deploy a forward corrective migration."
    )
