"""Add maker-checker full reversal for manual grants.

Revision ID: 0005_manual_grant_reversals
Revises: 0004_authority_registry
"""

from collections.abc import Sequence

from alembic import op


revision: str = "0005_manual_grant_reversals"
down_revision: str | None = "0004_authority_registry"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE bonus_ledger ADD COLUMN reversal_of_ledger_id BIGINT"
    )
    op.execute("""
        ALTER TABLE bonus_ledger
        ADD CONSTRAINT fk_bonus_ledger_reversal_origin
        FOREIGN KEY (reversal_of_ledger_id) REFERENCES bonus_ledger (id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
    """)
    op.execute(
        "CREATE UNIQUE INDEX idx_ledger_reversal_origin "
        "ON bonus_ledger (reversal_of_ledger_id) "
        "WHERE reversal_of_ledger_id IS NOT NULL"
    )
    op.execute("""
        CREATE TABLE manual_grant_reversals (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            grant_operation_id TEXT NOT NULL,
            original_ledger_id BIGINT NOT NULL,
            user_id BIGINT NOT NULL,
            amount BIGINT NOT NULL,
            reason TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            manual_reason TEXT,
            requested_by BIGINT NOT NULL,
            requested_at TIMESTAMPTZ NOT NULL,
            request_operation_id TEXT NOT NULL,
            request_hash TEXT NOT NULL,
            decided_by BIGINT,
            decided_at TIMESTAMPTZ,
            decision_note TEXT,
            decision_operation_id TEXT,
            decision_hash TEXT,
            reversal_ledger_id BIGINT,
            result_balance BIGINT,
            CONSTRAINT pk_manual_grant_reversals PRIMARY KEY (id),
            CONSTRAINT uq_manual_grant_reversal_request_operation
                UNIQUE (request_operation_id),
            CONSTRAINT uq_manual_grant_reversal_decision_operation
                UNIQUE (decision_operation_id),
            CONSTRAINT uq_manual_grant_reversal_ledger
                UNIQUE (reversal_ledger_id),
            CONSTRAINT fk_manual_grant_reversal_grant
                FOREIGN KEY (grant_operation_id)
                REFERENCES manual_grant_commands (operation_id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_manual_grant_reversal_original_ledger
                FOREIGN KEY (original_ledger_id) REFERENCES bonus_ledger (id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_manual_grant_reversal_user
                FOREIGN KEY (user_id) REFERENCES members (user_id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_manual_grant_reversal_requester
                FOREIGN KEY (requested_by) REFERENCES members (user_id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_manual_grant_reversal_checker
                FOREIGN KEY (decided_by) REFERENCES members (user_id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_manual_grant_reversal_ledger
                FOREIGN KEY (reversal_ledger_id) REFERENCES bonus_ledger (id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT ck_manual_grant_reversal_amount
                CHECK (amount BETWEEN 1 AND 200),
            CONSTRAINT ck_manual_grant_reversal_status CHECK (
                status IN ('pending','manual_required','applied','rejected')
            ),
            CONSTRAINT ck_manual_grant_reversal_maker_target
                CHECK (requested_by <> user_id),
            CONSTRAINT ck_manual_grant_reversal_checker_distinct CHECK (
                decided_by IS NULL OR (
                    decided_by <> requested_by AND decided_by <> user_id
                )
            )
        )
    """)
    op.execute(
        "CREATE INDEX idx_manual_grant_reversals_status "
        "ON manual_grant_reversals (status, requested_at, id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_manual_grant_one_pending_reversal "
        "ON manual_grant_reversals (grant_operation_id) "
        "WHERE status IN ('pending','manual_required')"
    )


def downgrade() -> None:
    raise RuntimeError(
        "Destructive manual-grant-reversal downgrade is disabled. Restore a "
        "verified backup or deploy a forward corrective migration."
    )
