"""Add versioned capability grants and maker-checker access changes.

Revision ID: 0007_capability_rbac
Revises: 0006_join_request_admission
"""

from collections.abc import Sequence
import json

from alembic import op


revision: str = "0007_capability_rbac"
down_revision: str | None = "0006_join_request_admission"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


CAPABILITIES_V1 = (
    "application.queue.view", "application.review", "member.search",
    "member.tags.view", "member.tags.manage", "member.city.review",
    "member.role.manage_basic", "task.view", "task.create", "task.cancel",
    "task.delivery.view", "task.delivery.retry", "task.template.manage",
    "admission.view", "admission.retry", "telegram.publication.manage",
    "task.review.queue", "task.review", "task.dispute.request",
    "task.dispute.decide", "bonus.grant.small", "bonus.reversal.request",
    "bonus.reversal.decide", "award.view", "award.grant", "award.revoke",
    "member.task_summary.view", "withdrawal.queue.view",
    "withdrawal.account.reveal", "withdrawal.handoff", "withdrawal.decide",
    "member.financial_summary.view", "access.view", "access.request",
    "access.decide", "award.catalog.manage", "telegram.inbox.redrive",
    "operations.health.view",
)


def _sql_literals(values):
    return ",".join("'" + value.replace("'", "''") + "'" for value in values)


def upgrade() -> None:
    preset_values = _sql_literals(("scout", "reviewer", "cashier", "owner"))
    capability_values = _sql_literals(CAPABILITIES_V1)
    op.execute(f"""
        CREATE TABLE staff_access_grants (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id BIGINT NOT NULL,
            preset TEXT NOT NULL,
            origin TEXT NOT NULL,
            status TEXT NOT NULL,
            policy_version INTEGER NOT NULL,
            generation INTEGER NOT NULL,
            granted_by BIGINT,
            approved_by BIGINT,
            grant_operation_id TEXT NOT NULL,
            granted_at TIMESTAMPTZ NOT NULL,
            revoked_by BIGINT,
            revoke_operation_id TEXT,
            revoked_at TIMESTAMPTZ,
            CONSTRAINT pk_staff_access_grants PRIMARY KEY (id),
            CONSTRAINT uq_staff_access_grants_grant_operation
                UNIQUE (grant_operation_id),
            CONSTRAINT uq_staff_access_grants_revoke_operation
                UNIQUE (revoke_operation_id),
            CONSTRAINT uq_staff_access_grants_generation
                UNIQUE (user_id,preset,origin,generation),
            CONSTRAINT fk_staff_access_grants_user FOREIGN KEY (user_id)
                REFERENCES members (user_id) ON DELETE RESTRICT
                DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT ck_staff_access_grants_preset
                CHECK (preset IN ({preset_values})),
            CONSTRAINT ck_staff_access_grants_origin
                CHECK (origin IN ('env','manual')),
            CONSTRAINT ck_staff_access_grants_status
                CHECK (status IN ('active','revoked')),
            CONSTRAINT ck_staff_access_grants_generation CHECK (generation > 0),
            CONSTRAINT ck_staff_access_grants_approver_distinct CHECK (
                approved_by IS NULL OR granted_by IS NULL OR approved_by<>granted_by
            )
        )
    """)
    op.execute(
        "CREATE UNIQUE INDEX idx_staff_access_one_active "
        "ON staff_access_grants (user_id,preset,origin) WHERE status='active'"
    )
    op.execute(f"""
        CREATE TABLE staff_grant_capabilities (
            grant_id BIGINT NOT NULL,
            capability TEXT NOT NULL,
            CONSTRAINT pk_staff_grant_capabilities
                PRIMARY KEY (grant_id, capability),
            CONSTRAINT fk_staff_grant_capabilities_grant FOREIGN KEY (grant_id)
                REFERENCES staff_access_grants (id) ON DELETE RESTRICT
                DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT ck_staff_grant_capabilities_capability
                CHECK (capability IN ({capability_values}))
        )
    """)
    op.execute(
        "CREATE INDEX idx_staff_grant_capability "
        "ON staff_grant_capabilities (capability,grant_id)"
    )
    op.execute(f"""
        CREATE TABLE staff_access_changes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            target_user_id BIGINT NOT NULL,
            change_action TEXT NOT NULL,
            preset TEXT NOT NULL,
            expected_generation INTEGER NOT NULL,
            reason TEXT NOT NULL,
            status TEXT NOT NULL,
            requested_by BIGINT NOT NULL,
            requested_at TIMESTAMPTZ NOT NULL,
            request_operation_id TEXT NOT NULL,
            request_hash TEXT NOT NULL,
            decided_by BIGINT,
            decided_at TIMESTAMPTZ,
            decision_note TEXT,
            decision_operation_id TEXT,
            decision_hash TEXT,
            result_json JSONB,
            CONSTRAINT pk_staff_access_changes PRIMARY KEY (id),
            CONSTRAINT uq_staff_access_changes_request_operation
                UNIQUE (request_operation_id),
            CONSTRAINT uq_staff_access_changes_decision_operation
                UNIQUE (decision_operation_id),
            CONSTRAINT fk_staff_access_changes_target FOREIGN KEY (target_user_id)
                REFERENCES members (user_id) ON DELETE RESTRICT
                DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT ck_staff_access_changes_action
                CHECK (change_action IN ('assign','revoke')),
            CONSTRAINT ck_staff_access_changes_preset
                CHECK (preset IN ({preset_values})),
            CONSTRAINT ck_staff_access_changes_status
                CHECK (status IN ('pending','applied','rejected')),
            CONSTRAINT ck_staff_access_changes_expected_generation
                CHECK (expected_generation >= 0),
            CONSTRAINT ck_staff_access_changes_requester_target
                CHECK (requested_by<>target_user_id),
            CONSTRAINT ck_staff_access_changes_checker_distinct CHECK (
                decided_by IS NULL OR (
                    decided_by<>requested_by AND decided_by<>target_user_id
                )
            )
        )
    """)
    op.execute(
        "CREATE UNIQUE INDEX idx_staff_access_one_pending "
        "ON staff_access_changes (target_user_id,preset) WHERE status='pending'"
    )
    op.execute(
        "CREATE INDEX idx_staff_access_changes_status "
        "ON staff_access_changes (status,requested_at,id)"
    )
    op.execute(f"""
        CREATE TABLE staff_access_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            target_user_id BIGINT NOT NULL,
            preset TEXT NOT NULL,
            event_type TEXT NOT NULL,
            actor_id BIGINT,
            operation_id TEXT NOT NULL,
            policy_version INTEGER NOT NULL,
            before_json JSONB NOT NULL,
            after_json JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            CONSTRAINT pk_staff_access_events PRIMARY KEY (id),
            CONSTRAINT uq_staff_access_events_operation UNIQUE (operation_id),
            CONSTRAINT fk_staff_access_events_target FOREIGN KEY (target_user_id)
                REFERENCES members (user_id) ON DELETE RESTRICT
                DEFERRABLE INITIALLY DEFERRED
        )
    """)

    # Existing authorities become a lossless policy-v1 owner projection. The
    # application role remains untouched; only approved members are imported.
    op.execute("""
        INSERT INTO staff_access_grants (
            user_id,preset,origin,status,policy_version,generation,
            granted_by,approved_by,grant_operation_id,granted_at
        )
        SELECT aa.user_id,'owner',aa.origin,'active',1,1,NULL,NULL,
               'rbac-v1-backfill:' || aa.user_id::text || ':' || aa.origin || ':' ||
               COALESCE(aa.granted_operation_id,'legacy'),aa.granted_at
        FROM admin_authorities aa
        JOIN members m ON m.user_id=aa.user_id
        WHERE m.status='approved' AND m.role='admin'
    """)
    op.execute(f"""
        INSERT INTO staff_grant_capabilities (grant_id,capability)
        SELECT g.id,c.capability
        FROM staff_access_grants g
        CROSS JOIN (VALUES {','.join(f"('{c}')" for c in CAPABILITIES_V1)})
            AS c(capability)
        WHERE g.preset='owner' AND g.policy_version=1 AND g.generation=1
    """)
    capabilities_json = json.dumps(
        sorted(CAPABILITIES_V1), ensure_ascii=False, separators=(",", ":"),
    ).replace("'", "''")
    op.execute(f"""
        INSERT INTO staff_access_events (
            target_user_id,preset,event_type,actor_id,operation_id,
            policy_version,before_json,after_json,created_at
        )
        SELECT g.user_id,g.preset,
               CASE WHEN g.origin='env' THEN 'env_sync' ELSE 'assign' END,
               NULL,'rbac-v1-event:' || g.user_id::text || ':' || g.origin || ':' ||
               g.generation::text,1,'{{}}'::jsonb,
               jsonb_build_object(
                   'preset','owner','origin',g.origin,'status','active',
                   'policy_version',1,'generation',1,
                   'capabilities','{capabilities_json}'::jsonb
               ),g.granted_at
        FROM staff_access_grants g
    """)


def downgrade() -> None:
    raise RuntimeError(
        "Destructive capability-RBAC downgrade is disabled. Restore a verified "
        "backup or deploy a forward corrective migration."
    )
