"""Add maker-checker award reversals with an immutable event trail.

Revision ID: 0009_award_reversals
Revises: 0008_task_template_versioning
"""

from collections.abc import Sequence

from alembic import op


revision: str = "0009_award_reversals"
down_revision: str | None = "0008_task_template_versioning"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE award_reversals (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            member_award_id BIGINT NOT NULL,
            original_ledger_id BIGINT,
            user_id BIGINT NOT NULL,
            award_id BIGINT NOT NULL,
            award_title TEXT NOT NULL,
            amount BIGINT NOT NULL,
            original_granted_by BIGINT,
            original_grant_operation_id TEXT,
            origin TEXT NOT NULL,
            status TEXT NOT NULL,
            manual_reason TEXT,
            reason TEXT NOT NULL,
            requested_by BIGINT,
            requested_at TIMESTAMPTZ,
            request_operation_id TEXT,
            request_hash TEXT,
            decided_by BIGINT,
            decided_at TIMESTAMPTZ,
            decision_note TEXT,
            decision_operation_id TEXT,
            decision_hash TEXT,
            reversal_ledger_id BIGINT,
            result_balance BIGINT,
            version INTEGER NOT NULL DEFAULT 1,
            CONSTRAINT pk_award_reversals PRIMARY KEY (id),
            CONSTRAINT uq_award_reversal_request_operation
                UNIQUE (request_operation_id),
            CONSTRAINT uq_award_reversal_decision_operation
                UNIQUE (decision_operation_id),
            CONSTRAINT uq_award_reversal_ledger UNIQUE (reversal_ledger_id),
            CONSTRAINT fk_award_reversal_member_award
                FOREIGN KEY (member_award_id) REFERENCES member_awards (id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_award_reversal_original_ledger
                FOREIGN KEY (original_ledger_id) REFERENCES bonus_ledger (id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_award_reversal_user
                FOREIGN KEY (user_id) REFERENCES members (user_id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_award_reversal_award
                FOREIGN KEY (award_id) REFERENCES awards (id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_award_reversal_original_granter
                FOREIGN KEY (original_granted_by) REFERENCES members (user_id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_award_reversal_requester
                FOREIGN KEY (requested_by) REFERENCES members (user_id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_award_reversal_checker
                FOREIGN KEY (decided_by) REFERENCES members (user_id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_award_reversal_ledger
                FOREIGN KEY (reversal_ledger_id) REFERENCES bonus_ledger (id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT ck_award_reversal_amount CHECK (
                amount >= 0 AND (origin <> 'maker_checker' OR amount <= 200)
            ),
            CONSTRAINT ck_award_reversal_origin CHECK (
                origin IN ('maker_checker','legacy_single_actor','legacy_unlinked')
            ),
            CONSTRAINT ck_award_reversal_status CHECK (
                status IN ('pending','manual_required','applied','rejected')
            ),
            CONSTRAINT ck_award_reversal_version CHECK (version > 0),
            CONSTRAINT ck_award_reversal_request_shape CHECK (
                origin <> 'maker_checker' OR (
                    requested_by IS NOT NULL AND requested_at IS NOT NULL
                    AND request_operation_id IS NOT NULL AND request_hash IS NOT NULL
                    AND requested_by <> user_id
                )
            ),
            CONSTRAINT ck_award_reversal_checker_distinct CHECK (
                origin <> 'maker_checker' OR decided_by IS NULL OR (
                    decided_by <> user_id
                    AND (requested_by IS NULL OR decided_by <> requested_by)
                    AND (original_granted_by IS NULL OR decided_by <> original_granted_by)
                )
            ),
            CONSTRAINT ck_award_reversal_decision_shape CHECK (
                origin <> 'maker_checker' OR (
                    (status IN ('pending','manual_required')
                     AND decided_by IS NULL AND decided_at IS NULL
                     AND decision_operation_id IS NULL AND decision_hash IS NULL
                     AND reversal_ledger_id IS NULL AND result_balance IS NULL)
                    OR
                    (status IN ('applied','rejected')
                     AND decided_by IS NOT NULL AND decided_at IS NOT NULL
                     AND decision_operation_id IS NOT NULL
                     AND decision_hash IS NOT NULL)
                )
            ),
            CONSTRAINT ck_award_reversal_grant_lineage CHECK (
                origin <> 'maker_checker' OR (
                    (amount=0 AND original_ledger_id IS NULL)
                    OR (amount>0 AND original_ledger_id IS NOT NULL
                        AND original_grant_operation_id IS NOT NULL)
                )
            ),
            CONSTRAINT ck_award_reversal_result_shape CHECK (
                origin <> 'maker_checker' OR status <> 'applied' OR (
                    (amount=0 AND reversal_ledger_id IS NULL
                     AND result_balance IS NOT NULL)
                    OR (amount>0 AND reversal_ledger_id IS NOT NULL
                        AND result_balance IS NOT NULL)
                )
            ),
            CONSTRAINT ck_award_reversal_rejected_result CHECK (
                origin <> 'maker_checker' OR status <> 'rejected' OR (
                    reversal_ledger_id IS NULL AND result_balance IS NULL
                )
            )
        )
    """)
    op.execute("""
        CREATE TABLE award_reversal_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reversal_id BIGINT NOT NULL,
            event_type TEXT NOT NULL,
            from_status TEXT,
            to_status TEXT NOT NULL,
            actor_id BIGINT,
            operation_id TEXT,
            created_at TIMESTAMPTZ NOT NULL,
            metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            CONSTRAINT pk_award_reversal_events PRIMARY KEY (id),
            CONSTRAINT uq_award_reversal_event_operation UNIQUE (operation_id),
            CONSTRAINT fk_award_reversal_event_reversal
                FOREIGN KEY (reversal_id) REFERENCES award_reversals (id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_award_reversal_event_actor
                FOREIGN KEY (actor_id) REFERENCES members (user_id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT ck_award_reversal_event_type CHECK (
                event_type IN (
                    'requested','manual_required','applied','rejected','legacy_imported'
                )
            ),
            CONSTRAINT ck_award_reversal_event_from_status CHECK (
                from_status IS NULL OR from_status IN (
                    'pending','manual_required','applied','rejected'
                )
            ),
            CONSTRAINT ck_award_reversal_event_to_status CHECK (
                to_status IN ('pending','manual_required','applied','rejected')
            )
        )
    """)
    op.execute(
        "CREATE INDEX idx_award_reversals_status "
        "ON award_reversals (status,requested_at,id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_award_reversal_one_pending "
        "ON award_reversals (member_award_id) "
        "WHERE status IN ('pending','manual_required')"
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_award_reversal_one_applied "
        "ON award_reversals (member_award_id) WHERE status='applied'"
    )
    op.execute(
        "CREATE INDEX idx_award_reversal_events_reversal "
        "ON award_reversal_events (reversal_id,id)"
    )

    # Preserve historical one-actor revocations without pretending they passed
    # maker-checker review. Ledger lineage is added only when both sides match
    # exactly; ambiguous history remains explicitly legacy_unlinked.
    op.execute("""
        INSERT INTO award_reversals (
            member_award_id,original_ledger_id,user_id,award_id,award_title,amount,
            original_granted_by,original_grant_operation_id,origin,status,reason,
            decided_by,decided_at,decision_note,reversal_ledger_id,result_balance,version
        )
        SELECT ma.id,origin_ledger.id,ma.user_id,ma.award_id,a.title,ma.bonus,
               grantor.user_id,ma.operation_id,
               CASE
                 WHEN ma.bonus=0 THEN 'legacy_single_actor'
                 WHEN origin_ledger.id IS NOT NULL AND reversal_ledger.id IS NOT NULL
                      AND (reversal_ledger.reversal_of_ledger_id IS NULL
                           OR reversal_ledger.reversal_of_ledger_id=origin_ledger.id)
                      AND NOT EXISTS (
                          SELECT 1 FROM bonus_ledger conflicting
                          WHERE conflicting.reversal_of_ledger_id=origin_ledger.id
                            AND conflicting.id<>reversal_ledger.id
                      )
                   THEN 'legacy_single_actor'
                 ELSE 'legacy_unlinked'
               END,
               'applied',COALESCE(ma.revoke_note,'Legacy award revocation'),
               legacy_actor.user_id,ma.revoked_at,ma.revoke_note,
               reversal_ledger.id,reversal_ledger.balance_after,1
        FROM member_awards ma
        JOIN awards a ON a.id=ma.award_id
        LEFT JOIN members grantor ON grantor.user_id=ma.granted_by
        LEFT JOIN members legacy_actor ON legacy_actor.user_id=ma.revoked_by
        LEFT JOIN bonus_ledger origin_ledger
          ON ma.operation_id IS NOT NULL
         AND origin_ledger.operation_id='award:' || ma.operation_id
         AND origin_ledger.user_id=ma.user_id
         AND origin_ledger.amount=ma.bonus
        LEFT JOIN bonus_ledger reversal_ledger
          ON ma.revoke_operation_id IS NOT NULL
         AND reversal_ledger.operation_id='award_revoke:' || ma.revoke_operation_id
         AND reversal_ledger.user_id=ma.user_id
         AND reversal_ledger.amount=-ma.bonus
        WHERE ma.revoked_at IS NOT NULL
    """)
    op.execute("""
        UPDATE bonus_ledger reversal
        SET reversal_of_ledger_id=r.original_ledger_id
        FROM award_reversals r
        WHERE r.origin='legacy_single_actor' AND r.amount>0
          AND r.reversal_ledger_id=reversal.id
          AND (reversal.reversal_of_ledger_id IS NULL
               OR reversal.reversal_of_ledger_id=r.original_ledger_id)
    """)
    op.execute("""
        INSERT INTO award_reversal_events (
            reversal_id,event_type,from_status,to_status,actor_id,operation_id,
            created_at,metadata_json
        )
        SELECT id,'legacy_imported',NULL,'applied',decided_by,NULL,
               COALESCE(decided_at,CURRENT_TIMESTAMP),
               jsonb_build_object('origin',origin)
        FROM award_reversals
    """)

    op.execute("""
        CREATE FUNCTION reject_award_reversal_event_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'award_reversal_events are immutable';
        END
        $$
    """)
    op.execute("""
        CREATE TRIGGER trg_award_reversal_events_immutable
        BEFORE UPDATE OR DELETE ON award_reversal_events
        FOR EACH ROW EXECUTE FUNCTION reject_award_reversal_event_mutation()
    """)


def downgrade() -> None:
    raise RuntimeError(
        "Destructive award-reversal downgrade is disabled. Restore a verified "
        "schema-299 backup or deploy a forward corrective migration."
    )
